import { ThemeConfig, ThemeId } from '../types';

export const THEMES: Record<ThemeId, ThemeConfig> = {
  'pure-black': {
    id: 'pure-black',
    name: 'Pure Black',
    tagline: 'Static AMOLED • Clean & Distraction-Free',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-black text-white',
    cardClass: 'bg-zinc-950/80 border border-zinc-900',
    borderClass: 'border-zinc-900',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-zinc-400 text-xs',
    accentClass: 'bg-cyan-400 text-black hover:bg-cyan-300 font-bold',
    accentGradient: 'from-cyan-400 to-blue-500 text-black',
    glowClass: 'shadow-none',
    bottomNavClass: 'bg-black/95 border-t border-zinc-900',
    headerClass: 'bg-black/95 border-b border-zinc-900',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-900 text-zinc-300 border border-zinc-800 hover:border-zinc-700',
    viewerBg: 'bg-black',
    playerAccent: '#00f3ff',
    previewGradient: 'bg-black border border-zinc-800',
  },
  'pure-white': {
    id: 'pure-white',
    name: 'Pure White',
    tagline: 'Bright & Clean • Minimal Focus',
    isPremium: false,
    type: 'static',
    bgClass: 'bg-white text-zinc-900',
    cardClass: 'bg-zinc-900/90 border border-zinc-800 text-white',
    borderClass: 'border-zinc-300',
    textPrimaryClass: 'text-zinc-900 font-bold',
    textSecondaryClass: 'text-zinc-600 text-xs',
    accentClass: 'bg-cyan-500 text-white hover:bg-cyan-600 font-bold',
    accentGradient: 'from-cyan-500 to-blue-600 text-white',
    glowClass: 'shadow-sm',
    bottomNavClass: 'bg-white/95 border-t border-zinc-200 text-zinc-900',
    headerClass: 'bg-white/95 border-b border-zinc-200 text-zinc-900',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-100 text-zinc-800 border border-zinc-300 hover:bg-zinc-200',
    viewerBg: 'bg-white',
    playerAccent: '#0284c7',
    previewGradient: 'bg-white border border-zinc-300',
  },
  'aurora-motion': {
    id: 'aurora-motion',
    name: 'Aurora Flow',
    tagline: 'Flowing Aurora Ribbons • Green, Cyan, Violet & Blue',
    isPremium: false,
    type: 'animated',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-zinc-950/75 border border-teal-500/25 backdrop-blur-md shadow-[0_10px_30px_rgba(0,0,0,0.5)]',
    borderClass: 'border-teal-500/25',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-teal-200/70 text-xs',
    accentClass: 'bg-teal-400 text-black hover:bg-teal-300 font-bold',
    accentGradient: 'from-emerald-400 via-teal-400 to-cyan-400 text-black',
    glowClass: 'shadow-[0_0_20px_rgba(45,212,191,0.15)]',
    bottomNavClass: 'bg-zinc-950/90 border-t border-teal-900/40 backdrop-blur-md',
    headerClass: 'bg-zinc-950/90 border-b border-teal-900/40 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-900/80 text-zinc-200 border border-zinc-800 hover:border-teal-400/50',
    viewerBg: 'bg-zinc-950',
    playerAccent: '#2dd4bf',
    previewGradient: 'bg-gradient-to-tr from-slate-950 via-teal-950 to-indigo-950',
  },
  'neon-flow': {
    id: 'neon-flow',
    name: 'Silk Wave',
    tagline: 'Dark Silver Silk Waves • Subtle Soft Reflections',
    isPremium: true,
    type: 'animated',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-black/80 border border-zinc-800/80 backdrop-blur-xl shadow-[0_10px_30px_rgba(0,0,0,0.8)]',
    borderClass: 'border-zinc-800/80',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-zinc-400 text-xs',
    accentClass: 'bg-zinc-200 text-black hover:bg-white font-bold',
    accentGradient: 'from-zinc-100 via-stone-300 to-zinc-400 text-black',
    glowClass: 'shadow-[0_0_20px_rgba(255,255,255,0.08)]',
    bottomNavClass: 'bg-black/95 border-t border-zinc-900 backdrop-blur-xl',
    headerClass: 'bg-black/95 border-b border-zinc-900 backdrop-blur-xl',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-950/90 text-zinc-200 border border-zinc-800 hover:border-zinc-600',
    viewerBg: 'bg-black',
    playerAccent: '#e4e4e7',
    previewGradient: 'bg-gradient-to-tr from-black via-zinc-950 to-neutral-900',
  },
  'cosmic-pulse': {
    id: 'cosmic-pulse',
    name: 'Digital Particle Space',
    tagline: 'Deep Particle Depth • Subtle Cyan Light Trails',
    isPremium: true,
    type: 'animated',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-zinc-950/80 border border-cyan-900/40 backdrop-blur-md shadow-md',
    borderClass: 'border-cyan-900/40',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-cyan-200/60 text-xs',
    accentClass: 'bg-cyan-400 text-black hover:bg-cyan-300 font-bold',
    accentGradient: 'from-cyan-400 via-blue-500 to-cyan-300 text-black',
    glowClass: 'shadow-[0_0_20px_rgba(34,211,238,0.15)]',
    bottomNavClass: 'bg-black/90 border-t border-cyan-950 backdrop-blur-md',
    headerClass: 'bg-black/90 border-b border-cyan-950 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-900/80 text-zinc-200 border border-zinc-800 hover:border-cyan-500/50',
    viewerBg: 'bg-black',
    playerAccent: '#22d3ee',
    previewGradient: 'bg-gradient-to-tr from-black via-zinc-950 to-cyan-950',
  },
  'prism-wave': {
    id: 'prism-wave',
    name: 'Organic Motion',
    tagline: 'Abstract Floating Leaves & Water • Soft Teal Rays',
    isPremium: true,
    type: 'animated',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-emerald-950/70 border border-teal-800/40 backdrop-blur-md shadow-md',
    borderClass: 'border-teal-800/40',
    textPrimaryClass: 'text-emerald-50 font-bold',
    textSecondaryClass: 'text-teal-200/70 text-xs',
    accentClass: 'bg-teal-400 text-black hover:bg-teal-300 font-bold',
    accentGradient: 'from-teal-400 via-emerald-400 to-cyan-300 text-black',
    glowClass: 'shadow-[0_0_25px_rgba(45,212,191,0.15)]',
    bottomNavClass: 'bg-emerald-950/90 border-t border-teal-900/50 backdrop-blur-md',
    headerClass: 'bg-emerald-950/90 border-b border-teal-900/50 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-emerald-950/80 text-emerald-100 border border-teal-900 hover:border-teal-400/50',
    viewerBg: 'bg-emerald-950',
    playerAccent: '#2dd4bf',
    previewGradient: 'bg-gradient-to-tr from-zinc-950 via-emerald-950 to-teal-950',
  },
  'liquid-spectrum': {
    id: 'liquid-spectrum',
    name: 'Cyber Rain',
    tagline: 'Falling Digital Energy • Cyan & Violet Pulses',
    isPremium: true,
    type: 'animated',
    bgClass: 'bg-transparent text-white',
    cardClass: 'bg-zinc-950/85 border border-cyan-500/30 backdrop-blur-md shadow-md',
    borderClass: 'border-cyan-500/30',
    textPrimaryClass: 'text-white font-bold',
    textSecondaryClass: 'text-cyan-200/70 text-xs',
    accentClass: 'bg-cyan-400 text-black hover:bg-cyan-300 font-bold',
    accentGradient: 'from-cyan-400 via-blue-500 to-violet-500 text-black',
    glowClass: 'shadow-[0_0_25px_rgba(34,211,238,0.2)]',
    bottomNavClass: 'bg-zinc-950/90 border-t border-cyan-900/50 backdrop-blur-md',
    headerClass: 'bg-zinc-950/90 border-b border-cyan-900/50 backdrop-blur-md',
    fontFamilyClass: 'font-sans',
    buttonClass: 'bg-zinc-900/80 text-zinc-200 border border-zinc-800 hover:border-cyan-400/50',
    viewerBg: 'bg-zinc-950',
    playerAccent: '#22d3ee',
    previewGradient: 'bg-gradient-to-tr from-black via-zinc-950 to-blue-950',
  },
};

export const DEFAULT_THEME_ID: ThemeId = 'pure-black';

export function getThemeConfig(themeId?: string): ThemeConfig {
  if (themeId && themeId in THEMES) {
    return THEMES[themeId as ThemeId];
  }
  return THEMES[DEFAULT_THEME_ID];
}
